application: reacdays
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: webapp/resources/index.html
  upload: webapp/resources(.*\.html)

- url: /bower_components
  static_dir: webapp/bower_components/

- url: /css
  static_dir: webapp/resources/public/css/

- url: /js
  static_dir: webapp/resources/public/js/

- url: /.*
  script: _go_app